[package]
name = "gspro-gc2-connector"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.10", features = ["derive"] }
env_logger = "0.11.4"
log = "0.4.22"
serialport = "4.4.0"
spin_sleep = "1.2.0"
